print("----------WELCOME----------")
r = int(input("Please enter the radius of circle:"))
circle_area = 3.14 * (r ** 2)
circle_perimeter = 3.14 * (r * 2)
sphere_area = 4 * 3.14 * (r ** 2)
sphere_volume = (4/3) * 3.14 * (r ** 3)
print("The area of the circle is:", circle_area)
print("The perimeter of the circle is:", circle_perimeter)
print("The area of the sphere is:", sphere_area)
print("The volume of the sphere is:", sphere_volume)

